version: 2.1

# Định nghĩa các orbs cần thiết cho Go
orbs:
  go: circleci/go@1.7.3

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.22 # Sử dụng image Go mới nhất
    steps:
      - checkout
      - go/load-cache # Tải cache dependencies
      - go/mod-download # Tải dependencies
      - go/save-cache # Lưu cache dependencies
      - run:
          name: Run tests
          command: go test -v ./...
      - run:
          name: Build application
          command: go build -v

  build-and-push-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce-cli
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            # Tạo tag từ git tag hoặc commit hash
            DOCKER_TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            
            # Build Docker image
            docker build -t $DOCKER_USERNAME/lab_4_circleci:latest -t $DOCKER_USERNAME/lab_4_circleci:$DOCKER_TAG .
            
            # Chạy container để test
            docker run -d -p 4000:4000 --name test-container $DOCKER_USERNAME/lab_4_circleci:latest
            
            # Đợi container khởi động
            sleep 10
            
            # Test API endpoint
            curl -f http://localhost:4000/ping || exit 1
            
            # Dừng và xóa container test
            docker stop test-container
            docker rm test-container
            
            # Push Docker images
            docker push $DOCKER_USERNAME/lab_4_circleci:latest
            docker push $DOCKER_USERNAME/lab_4_circleci:$DOCKER_TAG

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - build-and-push-docker:
          requires:
            - build-and-test
          filters:
            tags:
              only: /.*/
            branches:
              only: main